### ISSUE TITLE
Menu Lemonway pour le vendeur

### ISSUE THREAD

**Issue by pham-dat** [lemonwaysas/wordpress-woocommerce-webkul-lemonway-plugin#2]
@sirateck 
Je ne vois pas le menu Lemonway dans l'interface du vendeur.
Il faut l'ajouter à partir des widgets ?

**Comment by sirateck** [comment]
Salut @Crocodile29292,

On a réglé ce problème par téléphone il me semble ?

**Comment by sirateck** [comment]
@Crocodile29292 ,

tu peux revenir vers moi pour ce point.
De mon coté, cela fonctionne.
